# yaml-language-server: $schema=https://raw.githubusercontent.com/golangci/golangci-lint/refs/heads/main/jsonschema/golangci.jsonschema.json

version: "2"
linters:
  enable:
    - copyloopvar
    - cyclop
    - forbidigo
    - gocritic
    - gosec
    - govet
    - gochecknoglobals
    - revive
    - unconvert
    - noinlineerr
    - errcheck
    - errname
    - intrange
    - makezero
    - ineffassign
    - modernize
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - predeclared
    - reassign
    - recvcheck
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000 # https://staticcheck.dev/docs/checks/#ST1000
        - -ST1016 # https://staticcheck.dev/docs/checks/#ST1016
        - -QF1008 # https://staticcheck.dev/docs/checks/#QF1008
    nakedret:
      max-func-lines: 0
    cyclop:
      max-complexity: 10
    errcheck:
      check-blank: true
    gocritic:
      enabled-tags:
        - style
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
