#!/bin/sh
#/ script/overexported builds and runs the project with the given arguments.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

go build -o bin/overexported ./cmd/overexported

exec bin/overexported "$@"
